# Generated by Django 6.0.5 on 2026-05-17 05:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ObdMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('driver_behavior', models.CharField(max_length=50)),
                ('car_health', models.CharField(max_length=50)),
                ('engine_rpm', models.FloatField(blank=True, null=True)),
                ('vehicle_speed', models.FloatField(blank=True, null=True)),
                ('throttle', models.FloatField(blank=True, null=True)),
                ('engine_load', models.FloatField(blank=True, null=True)),
                ('coolant_temperature', models.FloatField(blank=True, null=True)),
                ('long_term_fuel_trim_bank_1', models.FloatField(blank=True, null=True)),
                ('short_term_fuel_trim_bank_1', models.FloatField(blank=True, null=True)),
                ('intake_manifold_pressure', models.FloatField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'obd_metrics',
                'ordering': ['timestamp'],
            },
        ),
    ]
